import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, expect, test, vi } from 'vitest'
import { createLayer, createSet, deleteLayer, deleteSet, getSetSounds, listLayers, listSets, listTags, reorderLayers, reorderSets, updateLayer, updateSet, type LayerRead, type SetRead, type SoundRead, type TagRead } from '../api/generated'
import { ConfigurationView } from './ConfigurationView'

vi.mock('../api/generated', () => ({ listLayers: vi.fn(), listSets: vi.fn(), listTags: vi.fn(), getSetSounds: vi.fn(), createLayer: vi.fn(), updateLayer: vi.fn(), deleteLayer: vi.fn(), createSet: vi.fn(), updateSet: vi.fn(), deleteSet: vi.fn(), reorderLayers: vi.fn(), reorderSets: vi.fn() }))
const mockLayers = vi.mocked(listLayers)
const mockSets = vi.mocked(listSets)
const mockCreate = vi.mocked(createLayer)
const mockUpdate = vi.mocked(updateLayer)
const mockDelete = vi.mocked(deleteLayer)
const mockTags = vi.mocked(listTags)
const mockMembers = vi.mocked(getSetSounds)
const mockCreateSet = vi.mocked(createSet)
const mockUpdateSet = vi.mocked(updateSet)
const mockDeleteSet = vi.mocked(deleteSet)
const mockReorderLayers = vi.mocked(reorderLayers)
const mockReorderSets = vi.mocked(reorderSets)

const layer = (id: string, name: string): LayerRead => ({ id, name, position: 0, playback_mode: 'single', volume: 80, created_at: '' })
const set = (id: string, layerId: string, name: string): SetRead => ({ id, layer_id: layerId, name, position: 0, loop: false, shuffle: true, tags: [], created_at: '' })

beforeEach(() => {
  mockLayers.mockReset()
  mockSets.mockReset()
  mockCreate.mockReset()
  mockUpdate.mockReset()
  mockDelete.mockReset()
  mockTags.mockReset()
  mockMembers.mockReset()
  mockCreateSet.mockReset()
  mockUpdateSet.mockReset()
  mockDeleteSet.mockReset()
  mockReorderLayers.mockReset()
  mockReorderSets.mockReset()
  mockTags.mockResolvedValue({ data: [] } as never)
  mockMembers.mockResolvedValue({ data: [] } as never)
})

test('Add Layer is an unsaved draft and Save creates it with defaults', async () => {
  mockLayers.mockResolvedValue({ data: [layer('a', 'Music')] } as never)
  mockSets.mockResolvedValue({ data: [] } as never)
  mockCreate.mockResolvedValue({ data: layer('b', 'Rain') } as never)
  render(<ConfigurationView />)
  fireEvent.click(await screen.findByRole('button', { name: 'Add Layer' }))
  expect(mockCreate).not.toHaveBeenCalled()
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: 'Rain' } })
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  await waitFor(() => expect(mockCreate).toHaveBeenCalledWith({ body: { name: 'Rain', playback_mode: 'single', volume: 80 } }))
  expect(await screen.findByRole('region', { name: 'Rain' })).toBeInTheDocument()
})

test('shows loading, then preserves server order and selects a Set', async () => {
  mockLayers.mockResolvedValue({ data: [layer('b', 'Music'), layer('a', 'Ambience')] } as never)
  mockSets.mockImplementation(({ path }) => Promise.resolve({ data: path.layer_id === 'b' ? [set('y', 'b', 'Finale'), set('x', 'b', 'Intro')] : [] }) as never)

  render(<ConfigurationView />)
  expect(screen.getByRole('status')).toHaveTextContent('Loading Layers & Sets')
  const outline = await screen.findByRole('region', { name: 'Outline' })
  expect(within(outline).getAllByRole('button', { name: /Music|Finale|Intro|Ambience/ }).length).toBeGreaterThan(3)
  expect(within(screen.getByRole('region', { name: 'Music' })).getByRole('textbox', { name: 'Volume' })).toHaveValue('80')
  expect(within(outline).getByRole('button', { name: 'Music' })).toHaveAttribute('aria-current', 'true')
  fireEvent.click(within(outline).getByRole('button', { name: 'Finale' }))
  expect(screen.getByRole('region', { name: 'Finale' })).toHaveTextContent('Music / Set')
  await waitFor(() => expect(screen.getByRole('heading', { name: 'Finale' })).toHaveFocus())
  expect(screen.getByRole('region', { name: 'Finale' })).toHaveTextContent('No Tags selected')
  expect(within(outline).getByRole('button', { name: 'Finale' })).toHaveAttribute('aria-current', 'true')
})

test('keeps selection after refresh and falls back when its Set disappears', async () => {
  mockLayers.mockResolvedValue({ data: [layer('a', 'Ambience')] } as never)
  mockSets.mockResolvedValueOnce({ data: [set('x', 'a', 'Rain')] } as never)
  mockSets.mockResolvedValueOnce({ data: [set('x', 'a', 'Rain updated')] } as never)
  mockSets.mockResolvedValueOnce({ data: [] } as never)
  render(<ConfigurationView />)
  fireEvent.click(await screen.findByRole('button', { name: 'Rain' }))
  fireEvent.click(screen.getByRole('button', { name: 'Refresh' }))
  expect(await screen.findByRole('region', { name: 'Rain updated' })).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Refresh' }))
  expect(within(await screen.findByRole('region', { name: 'Ambience' })).getByRole('textbox', { name: 'Volume' })).toHaveValue('80')
  await waitFor(() => expect(screen.getByRole('heading', { name: 'Ambience' })).toHaveFocus())
  expect(screen.getByText('No Sets in this Layer')).toBeInTheDocument()
})

test('shows retry on failure and a first-Layer action for an empty account', async () => {
  mockLayers.mockResolvedValueOnce({ error: { detail: 'Unavailable' } } as never)
  mockLayers.mockResolvedValueOnce({ data: [] } as never)
  render(<ConfigurationView />)
  expect(await screen.findByRole('alert')).toHaveTextContent('Unavailable')
  fireEvent.click(screen.getByRole('button', { name: 'Try again' }))
  expect(await screen.findByRole('heading', { name: 'No Layers yet' })).toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'Create first Layer' })).toBeEnabled()
  expect(screen.queryByRole('region', { name: /settings/i })).not.toBeInTheDocument()
})

test('reports a Set fetch error without showing a partial outline', async () => {
  mockLayers.mockResolvedValue({ data: [layer('a', 'Ambience')] } as never)
  mockSets.mockResolvedValue({ error: { detail: 'Set request failed' } } as never)
  render(<ConfigurationView />)
  expect(await screen.findByRole('alert')).toHaveTextContent('Set request failed')
  expect(screen.queryByRole('region', { name: 'Outline' })).not.toBeInTheDocument()
})

const load = (layers: LayerRead[], setsByLayer: Record<string, SetRead[]> = {}) => {
  mockLayers.mockResolvedValue({ data: layers } as never)
  mockSets.mockImplementation(({ path }) => Promise.resolve({ data: setsByLayer[path.layer_id] ?? [] }) as never)
  render(<ConfigurationView />)
}

test('first Layer starts with server defaults and is created only on Save', async () => {
  load([])
  fireEvent.click(await screen.findByRole('button', { name: 'Create first Layer' }))
  expect(mockCreate).not.toHaveBeenCalled()
  expect(screen.getByRole('combobox', { name: 'Playback mode' })).toHaveValue('single')
  expect(screen.getByRole('textbox', { name: 'Volume' })).toHaveValue('80')
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  expect(screen.getByText('Enter a Layer name.')).toBeInTheDocument()
  expect(mockCreate).not.toHaveBeenCalled()
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: 'Music' } })
  mockCreate.mockResolvedValue({ data: layer('a', 'Music') } as never)
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  expect(await screen.findByRole('region', { name: 'Music' })).toBeInTheDocument()
  expect(screen.queryByRole('heading', { name: 'No Layers yet' })).not.toBeInTheDocument()
})

test.each([
  ['whitespace', ' \u2003 ', 'Enter a Layer name.'],
  ['too long', 'a'.repeat(101), 'Layer name must be 100 characters or fewer.'],
  ['control character', 'Bad\u0000name', 'Layer name must not contain control characters.'],
])('keeps %s name drafts and does not submit them', async (_case, value, message) => {
  load([layer('a', 'Music')])
  fireEvent.click(await screen.findByRole('button', { name: 'Add Layer' }))
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value } })
  expect(screen.getByText(message)).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  expect(mockCreate).not.toHaveBeenCalled()
  expect(screen.getByRole('textbox', { name: 'Name' })).toHaveValue(value)
})

test.each(['', '-1', '101', '1.5', '1e2'])('rejects invalid volume draft %s', async (value) => {
  load([layer('a', 'Music')])
  await screen.findByRole('region', { name: 'Music' })
  fireEvent.change(screen.getByRole('textbox', { name: 'Volume' }), { target: { value } })
  expect(screen.getByText('Volume must be a whole number from 0 to 100.')).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  expect(mockUpdate).not.toHaveBeenCalled()
})

test('edit is staged, Cancel resets, and successful save uses canonical server values', async () => {
  load([layer('a', 'Music')])
  await screen.findByRole('region', { name: 'Music' })
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: '  Rain  ' } })
  fireEvent.change(screen.getByRole('combobox', { name: 'Playback mode' }), { target: { value: 'multiset' } })
  fireEvent.change(screen.getByRole('textbox', { name: 'Volume' }), { target: { value: '0' } })
  expect(mockUpdate).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'Cancel changes' }))
  expect(screen.getByRole('textbox', { name: 'Name' })).toHaveValue('Music')
  expect(screen.getByRole('textbox', { name: 'Volume' })).toHaveValue('80')
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: '  Rain  ' } })
  fireEvent.change(screen.getByRole('combobox', { name: 'Playback mode' }), { target: { value: 'self_stacking' } })
  fireEvent.change(screen.getByRole('textbox', { name: 'Volume' }), { target: { value: '100' } })
  mockUpdate.mockResolvedValue({ data: { ...layer('a', 'Rain'), playback_mode: 'self_stacking', volume: 100 } } as never)
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  await waitFor(() => expect(mockUpdate).toHaveBeenCalledWith({ path: { layer_id: 'a' }, body: { name: 'Rain', playback_mode: 'self_stacking', volume: 100 } }))
  expect(await screen.findByRole('region', { name: 'Rain' })).toBeInTheDocument()
  expect(screen.getByRole('textbox', { name: 'Name' })).toHaveValue('Rain')
})

test('server 422 and general save failures retain the editable draft', async () => {
  load([layer('a', 'Music')])
  await screen.findByRole('region', { name: 'Music' })
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: 'Rain' } })
  mockUpdate.mockResolvedValueOnce({ error: { detail: [{ msg: 'Server rejected name' }] } } as never)
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Server rejected name')
  expect(screen.getByRole('textbox', { name: 'Name' })).toHaveValue('Rain')
  expect(screen.getByRole('button', { name: 'Music' })).toBeInTheDocument()
  mockUpdate.mockRejectedValueOnce(new Error('Network failed'))
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Network failed')
  expect(screen.getByRole('textbox', { name: 'Name' })).toHaveValue('Rain')
})

test('duplicate Layer names are allowed and canonical create response drives the outline', async () => {
  load([layer('a', 'Music')])
  fireEvent.click(await screen.findByRole('button', { name: 'Add Layer' }))
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: ' Music ' } })
  mockCreate.mockResolvedValue({ data: layer('b', 'Music') } as never)
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  await waitFor(() => expect(mockCreate).toHaveBeenCalledWith({ body: { name: 'Music', playback_mode: 'single', volume: 80 } }))
  expect(within(screen.getByRole('region', { name: 'Outline' })).getAllByRole('button', { name: 'Music' })).toHaveLength(2)
})

test('delete confirms cascading Set count, selects a neighbor, then offers first-Layer creation', async () => {
  load([layer('a', 'Music'), layer('b', 'Rain')], { a: [set('x', 'a', 'Storm'), set('y', 'a', 'Wind')] })
  await screen.findByRole('region', { name: 'Music' })
  fireEvent.click(screen.getByRole('button', { name: 'Delete Layer' }))
  const dialog = screen.getByRole('dialog', { name: 'Delete Layer Music?' })
  expect(dialog).toHaveTextContent('2 Sets')
  expect(dialog).toHaveTextContent('Library Sounds are unaffected')
  expect(mockDelete).not.toHaveBeenCalled()
  fireEvent.click(within(dialog).getByRole('button', { name: 'Cancel' }))
  expect(mockDelete).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'Delete Layer' }))
  mockDelete.mockResolvedValue({} as never)
  fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Delete Layer' }))
  await waitFor(() => expect(mockDelete).toHaveBeenCalledWith({ path: { layer_id: 'a' } }))
  expect(await screen.findByRole('region', { name: 'Rain' })).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Delete Layer' }))
  mockDelete.mockResolvedValue({} as never)
  fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Delete Layer' }))
  expect(await screen.findByRole('heading', { name: 'No Layers yet' })).toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'Create first Layer' })).toBeEnabled()
})

test('100 Unicode code points and Unicode edge whitespace are valid', async () => {
  load([layer('a', 'Music')])
  fireEvent.click(await screen.findByRole('button', { name: 'Add Layer' }))
  const name = '🎵'.repeat(100)
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: `\u2003${name}\u2003` } })
  mockCreate.mockResolvedValue({ data: layer('b', name) } as never)
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  await waitFor(() => expect(mockCreate).toHaveBeenCalledWith({ body: { name, playback_mode: 'single', volume: 80 } }))
})

test('a one-code-point name is valid at the lower boundary', async () => {
  load([layer('a', 'Music')])
  fireEvent.click(await screen.findByRole('button', { name: 'Add Layer' }))
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: '🎵' } })
  mockCreate.mockResolvedValue({ data: layer('b', '🎵') } as never)
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  await waitFor(() => expect(mockCreate).toHaveBeenCalledWith({ body: { name: '🎵', playback_mode: 'single', volume: 80 } }))
})

test('a Unicode Cc character inside a name is rejected', async () => {
  load([layer('a', 'Music')])
  fireEvent.click(await screen.findByRole('button', { name: 'Add Layer' }))
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: 'Bad\u0085name' } })
  expect(screen.getByText('Layer name must not contain control characters.')).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  expect(mockCreate).not.toHaveBeenCalled()
})

test('pending save and delete cannot submit twice', async () => {
  load([layer('a', 'Music')])
  await screen.findByRole('region', { name: 'Music' })
  let finishSave: (result: unknown) => void = () => { throw new Error('missing resolver') }
  mockUpdate.mockImplementation(() => new Promise((resolve) => { finishSave = resolve }) as never)
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  expect(screen.getByRole('button', { name: 'Saving…' })).toBeDisabled()
  expect(mockUpdate).toHaveBeenCalledTimes(1)
  finishSave({ data: layer('a', 'Music') })
  await screen.findByRole('status')
  fireEvent.click(screen.getByRole('button', { name: 'Delete Layer' }))
  let finishDelete: (result: unknown) => void = () => { throw new Error('missing resolver') }
  mockDelete.mockImplementation(() => new Promise((resolve) => { finishDelete = resolve }) as never)
  fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Delete Layer' }))
  expect(within(screen.getByRole('dialog')).getByRole('button', { name: 'Deleting…' })).toBeDisabled()
  expect(mockDelete).toHaveBeenCalledTimes(1)
  finishDelete({})
  expect(await screen.findByRole('heading', { name: 'No Layers yet' })).toBeInTheDocument()
})

test('failed delete reports the error and preserves the Layer', async () => {
  load([layer('a', 'Music')])
  await screen.findByRole('region', { name: 'Music' })
  fireEvent.click(screen.getByRole('button', { name: 'Delete Layer' }))
  mockDelete.mockResolvedValue({ error: { detail: 'Delete failed' } } as never)
  fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Delete Layer' }))
  expect(await screen.findByRole('status')).toHaveTextContent('Delete failed')
  expect(screen.getByRole('region', { name: 'Music' })).toBeInTheDocument()
})

const tag = (id: string, name: string): TagRead => ({ id, name, created_at: '' })
const sound = (id: string, name: string, kind: SoundRead['kind'], is_errored = false): SoundRead => ({
  id, name, kind, is_errored, error_detail: null, content_type: null, created_at: '',
  duration_seconds: null, tags: [], youtube_video_id: null,
})

test('creates a tagless Set only on Save and selects the saved Set', async () => {
  load([layer('a', 'Music')])
  fireEvent.click(await screen.findByRole('button', { name: 'Add Set to Music' }))
  expect(mockCreateSet).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  expect(screen.getByText('Enter a Set name.')).toBeInTheDocument()
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: '  Rain  ' } })
  mockCreateSet.mockResolvedValue({ data: set('x', 'a', 'Rain') } as never)
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  await waitFor(() => expect(mockCreateSet).toHaveBeenCalledWith({ path: { layer_id: 'a' }, body: { name: 'Rain', tagIds: [], loop: false, shuffle: false } }))
  expect(await screen.findByText('No Tags selected. Select Tags to include Sounds.')).toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'Rain' })).toHaveAttribute('aria-current', 'true')
})

test('Set changes stage and reset; clearing final Tag sends an explicit empty list', async () => {
  mockTags.mockResolvedValue({ data: [tag('t', 'weather'), tag('u', 'storm')] } as never)
  load([layer('a', 'Music')], { a: [{ ...set('x', 'a', 'Rain'), tags: [tag('t', 'weather')], shuffle: false }] })
  fireEvent.click(await screen.findByRole('button', { name: 'Rain' }))
  fireEvent.click(screen.getByRole('checkbox', { name: 'weather' }))
  fireEvent.click(screen.getByRole('checkbox', { name: 'Loop' }))
  fireEvent.click(screen.getByRole('checkbox', { name: 'Shuffle' }))
  fireEvent.click(screen.getByRole('button', { name: 'Cancel changes' }))
  expect(screen.getByRole('checkbox', { name: 'weather' })).toBeChecked()
  expect(screen.getByRole('checkbox', { name: 'Loop' })).not.toBeChecked()
  fireEvent.click(screen.getByRole('checkbox', { name: 'weather' }))
  fireEvent.click(screen.getByRole('checkbox', { name: 'Loop' }))
  fireEvent.click(screen.getByRole('checkbox', { name: 'Shuffle' }))
  mockUpdateSet.mockResolvedValue({ data: { ...set('x', 'a', 'Rain'), loop: true } } as never)
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  await waitFor(() => expect(mockUpdateSet).toHaveBeenCalledWith({ path: { set_id: 'x' }, body: { tagIds: [], loop: true, shuffle: true } }))
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  await waitFor(() => expect(mockUpdateSet).toHaveBeenLastCalledWith({ path: { set_id: 'x' }, body: {} }))
})

test('new Set uses the full selected Tag list and retains its draft after a failed create', async () => {
  mockTags.mockResolvedValue({ data: [tag('t', 'weather'), tag('u', 'storm')] } as never)
  load([layer('a', 'Music')])
  fireEvent.click(await screen.findByRole('button', { name: 'Add Set to Music' }))
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: 'Rain' } })
  fireEvent.click(screen.getByRole('checkbox', { name: 'weather' }))
  fireEvent.click(screen.getByRole('checkbox', { name: 'storm' }))
  fireEvent.click(screen.getByRole('checkbox', { name: 'Loop' }))
  mockCreateSet.mockResolvedValueOnce({ error: { detail: 'Unavailable' } } as never)
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Unavailable')
  expect(screen.getByRole('textbox', { name: 'Name' })).toHaveValue('Rain')
  expect(screen.getByRole('checkbox', { name: 'storm' })).toBeChecked()
  mockCreateSet.mockResolvedValue({ data: { ...set('x', 'a', 'Rain'), tags: [tag('t', 'weather'), tag('u', 'storm')], loop: true, shuffle: false } } as never)
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  await waitFor(() => expect(mockCreateSet).toHaveBeenLastCalledWith({ path: { layer_id: 'a' }, body: { name: 'Rain', tagIds: ['t', 'u'], loop: true, shuffle: false } }))
})

test('existing User Tags are available after creating the first Layer', async () => {
  mockTags.mockResolvedValue({ data: [tag('t', 'weather')] } as never)
  load([])
  fireEvent.click(await screen.findByRole('button', { name: 'Create first Layer' }))
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: 'Music' } })
  mockCreate.mockResolvedValue({ data: layer('a', 'Music') } as never)
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  fireEvent.click(await screen.findByRole('button', { name: 'Add Set to Music' }))
  expect(screen.getByRole('checkbox', { name: 'weather' })).toBeInTheDocument()
})

test('Set API failure preserves the draft and membership shows server order, sources, and errors', async () => {
  mockTags.mockResolvedValue({ data: [tag('t', 'weather')] } as never)
  mockMembers.mockResolvedValue({ data: [sound('1', 'Zulu', 'youtube', true), sound('2', 'Alpha', 'file')] } as never)
  load([layer('a', 'Music')], { a: [{ ...set('x', 'a', 'Rain'), tags: [tag('t', 'weather')] }] })
  fireEvent.click(await screen.findByRole('button', { name: 'Rain' }))
  const members = await screen.findByRole('region', { name: 'Resolved membership' })
  await waitFor(() => expect(within(members).getByText('2 Sounds')).toBeInTheDocument())
  expect(within(members).getAllByRole('listitem').map((item) => item.textContent)).toEqual(['Zulu — YouTube — Errored', 'Alpha — Uploaded file'])
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: 'Storm' } })
  mockUpdateSet.mockResolvedValue({ error: { detail: 'Save failed' } } as never)
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Save failed')
  expect(screen.getByRole('textbox', { name: 'Name' })).toHaveValue('Storm')
})

test('membership distinguishes selected Tags with no matches and refreshes after save', async () => {
  mockTags.mockResolvedValue({ data: [tag('t', 'weather')] } as never)
  load([layer('a', 'Music')], { a: [{ ...set('x', 'a', 'Rain'), tags: [tag('t', 'weather')] }] })
  fireEvent.click(await screen.findByRole('button', { name: 'Rain' }))
  expect(await screen.findByText(/No matching Sounds/)).toBeInTheDocument()
  mockUpdateSet.mockResolvedValue({ data: { ...set('x', 'a', 'Rain'), tags: [tag('t', 'weather')], loop: true } } as never)
  fireEvent.click(screen.getByRole('checkbox', { name: 'Loop' }))
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  await waitFor(() => expect(mockMembers).toHaveBeenCalledTimes(2))
})

test('workspace refresh replaces stale Tag selections after a Tag is deleted', async () => {
  mockLayers.mockResolvedValue({ data: [layer('a', 'Music')] } as never)
  mockSets.mockResolvedValueOnce({ data: [{ ...set('x', 'a', 'Rain'), tags: [tag('t', 'weather')] }] } as never)
  mockSets.mockResolvedValueOnce({ data: [set('x', 'a', 'Rain')] } as never)
  mockTags.mockResolvedValueOnce({ data: [tag('t', 'weather')] } as never)
  mockTags.mockResolvedValueOnce({ data: [] } as never)
  render(<ConfigurationView />)
  fireEvent.click(await screen.findByRole('button', { name: 'Rain' }))
  expect(screen.getByRole('checkbox', { name: 'weather' })).toBeChecked()
  fireEvent.click(screen.getByRole('button', { name: 'Refresh' }))
  expect(await screen.findByText('No Tags selected. Select Tags to include Sounds.')).toBeInTheDocument()
  expect(screen.queryByRole('checkbox', { name: 'weather' })).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  await waitFor(() => expect(mockUpdateSet).toHaveBeenCalledWith({ path: { set_id: 'x' }, body: {} }))
})

test('Set deletion confirms Library Sounds stay and selects a sibling', async () => {
  load([layer('a', 'Music')], { a: [set('x', 'a', 'Rain'), set('y', 'a', 'Wind')] })
  fireEvent.click(await screen.findByRole('button', { name: 'Rain' }))
  fireEvent.click(screen.getByRole('button', { name: 'Delete Set' }))
  const dialog = screen.getByRole('dialog', { name: 'Delete Set Rain?' })
  expect(dialog).toHaveTextContent('Matching Library Sounds are unaffected')
  mockDeleteSet.mockResolvedValue({} as never)
  fireEvent.click(within(dialog).getByRole('button', { name: 'Delete Set' }))
  await waitFor(() => expect(mockDeleteSet).toHaveBeenCalledWith({ path: { set_id: 'x' } }))
  expect(await screen.findByRole('region', { name: 'Wind' })).toBeInTheDocument()
})

const outlineNames = (kind: 'layer' | 'set') => {
  const outline = screen.getByRole('region', { name: 'Outline' })
  const selector = kind === 'layer'
    ? ':scope > ul > li > .outline-row > .outline-item'
    : 'ul ul > li > .outline-row > .outline-item'
  return Array.from(outline.querySelectorAll(selector)).map((item) => item.textContent?.replace('No Tags selected', ''))
}

test('Layer move is keyboard reachable, optimistic, immediate, and reconciles to server order without losing a draft', async () => {
  const user = userEvent.setup()
  load([layer('a', 'Music'), layer('b', 'Ambience'), layer('c', 'Effects')])
  await screen.findByRole('button', { name: 'Move Layer Ambience up' })
  fireEvent.change(screen.getByRole('textbox', { name: 'Volume' }), { target: { value: '42' } })
  let finish: (result: unknown) => void = () => { throw new Error('missing resolver') }
  mockReorderLayers.mockImplementation(() => new Promise((resolve) => { finish = resolve }) as never)
  const move = screen.getByRole('button', { name: 'Move Layer Ambience up' })
  move.focus()
  expect(move).toHaveFocus()
  await user.keyboard('{Enter}')
  expect(mockReorderLayers).toHaveBeenCalledWith({ body: { ordered_ids: ['b', 'a', 'c'] } })
  expect(outlineNames('layer')).toEqual(['Ambience', 'Music', 'Effects'])
  expect(screen.getByRole('button', { name: 'Move Layer Effects up' })).toBeDisabled()
  expect(screen.getByRole('button', { name: 'Move Layer Music down' })).toBeDisabled()
  expect(screen.getByRole('button', { name: 'Music' })).toHaveAttribute('aria-current', 'true')
  expect(screen.getByRole('textbox', { name: 'Volume' })).toHaveValue('42')
  finish({ data: [layer('c', 'Effects'), layer('b', 'Ambience'), layer('a', 'Music')] })
  await waitFor(() => expect(outlineNames('layer')).toEqual(['Effects', 'Ambience', 'Music']))
  expect(screen.getByRole('textbox', { name: 'Volume' })).toHaveValue('42')
  expect(mockUpdate).not.toHaveBeenCalled()
})

test('failed Layer move restores the entire order and keeps the selected Layer and its draft', async () => {
  load([layer('a', 'First'), layer('b', 'Second'), layer('c', 'Third')])
  fireEvent.click(await screen.findByRole('button', { name: 'Second' }))
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: 'Draft name' } })
  mockReorderLayers.mockResolvedValue({ error: { detail: 'Order conflict' } } as never)
  fireEvent.click(screen.getByRole('button', { name: 'Move Layer Second down' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Order conflict')
  expect(outlineNames('layer')).toEqual(['First', 'Second', 'Third'])
  expect(screen.getByRole('button', { name: 'Second' })).toHaveAttribute('aria-current', 'true')
  expect(screen.getByRole('textbox', { name: 'Name' })).toHaveValue('Draft name')
  expect(mockUpdate).not.toHaveBeenCalled()
})

test('Set move stays within its Layer, sends every sibling ID, and preserves a Set draft', async () => {
  const user = userEvent.setup()
  load([layer('a', 'Music'), layer('b', 'Other')], {
    a: [set('x', 'a', 'Intro'), set('y', 'a', 'Middle'), set('z', 'a', 'Finale')],
    b: [set('q', 'b', 'Only')],
  })
  fireEvent.click(await screen.findByRole('button', { name: 'Middle' }))
  await waitFor(() => expect(screen.getByRole('heading', { name: 'Middle' })).toHaveFocus())
  fireEvent.click(screen.getByRole('checkbox', { name: 'Loop' }))
  let finish: (result: unknown) => void = () => { throw new Error('missing resolver') }
  mockReorderSets.mockImplementation(() => new Promise((resolve) => { finish = resolve }) as never)
  screen.getByRole('button', { name: 'Move Set Middle up' }).focus()
  await user.keyboard(' ')
  expect(mockReorderSets).toHaveBeenCalledWith({ path: { layer_id: 'a' }, body: { ordered_ids: ['y', 'x', 'z'] } })
  expect(outlineNames('set')).toEqual(['Middle', 'Intro', 'Finale', 'Only'])
  expect(screen.getByRole('button', { name: 'Move Set Only up' })).toBeDisabled()
  expect(screen.getByRole('button', { name: 'Move Set Only down' })).toBeDisabled()
  expect(screen.getByRole('checkbox', { name: 'Loop' })).toBeChecked()
  expect(screen.getByRole('button', { name: 'Middle' })).toHaveAttribute('aria-current', 'true')
  finish({ data: [set('z', 'a', 'Finale'), set('y', 'a', 'Middle'), set('x', 'a', 'Intro')] })
  await waitFor(() => expect(outlineNames('set')).toEqual(['Finale', 'Middle', 'Intro', 'Only']))
  expect(screen.getByRole('checkbox', { name: 'Loop' })).toBeChecked()
})

test('failed Set move restores sibling order, announces the error, and retains selection and draft', async () => {
  load([layer('a', 'Custom')], { a: [set('x', 'a', 'One'), set('y', 'a', 'Two'), set('z', 'a', 'Three')] })
  fireEvent.click(await screen.findByRole('button', { name: 'Two' }))
  fireEvent.change(screen.getByRole('textbox', { name: 'Name' }), { target: { value: 'Unsaved' } })
  mockReorderSets.mockRejectedValue(new Error('Network unavailable'))
  fireEvent.click(screen.getByRole('button', { name: 'Move Set Two down' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Network unavailable')
  expect(outlineNames('set')).toEqual(['One', 'Two', 'Three'])
  expect(screen.getByRole('button', { name: 'Two' })).toHaveAttribute('aria-current', 'true')
  expect(screen.getByRole('textbox', { name: 'Name' })).toHaveValue('Unsaved')
  expect(mockUpdateSet).not.toHaveBeenCalled()
})

test('unchanged boundary moves do not call an API even for duplicate names', async () => {
  load([layer('a', 'Same'), layer('b', 'Same')], { a: [set('x', 'a', 'Same')] })
  await screen.findByRole('region', { name: 'Outline' })
  const outline = screen.getByRole('region', { name: 'Outline' })
  const firstLayerUp = within(outline.querySelector('ul > li') as HTMLElement).getByRole('button', { name: 'Move Layer Same up' })
  expect(firstLayerUp).toBeDisabled()
  expect(screen.getByRole('button', { name: 'Move Set Same up' })).toBeDisabled()
  expect(screen.getByRole('button', { name: 'Move Set Same down' })).toBeDisabled()
  expect(mockReorderLayers).not.toHaveBeenCalled()
  expect(mockReorderSets).not.toHaveBeenCalled()
  mockReorderLayers.mockResolvedValue({ data: [layer('b', 'Same'), layer('a', 'Same')] } as never)
  const secondLayer = outline.querySelector(':scope > ul > li:nth-child(2)') as HTMLElement
  fireEvent.click(within(secondLayer).getByRole('button', { name: 'Move Layer Same up' }))
  await waitFor(() => expect(mockReorderLayers).toHaveBeenCalledWith({ body: { ordered_ids: ['b', 'a'] } }))
})

test('pending reorder blocks saves and deletes, and pending save blocks reorder', async () => {
  load([layer('a', 'First'), layer('b', 'Second')])
  await screen.findByRole('button', { name: 'Move Layer First down' })
  let finishReorder: (result: unknown) => void = () => { throw new Error('missing resolver') }
  mockReorderLayers.mockImplementation(() => new Promise((resolve) => { finishReorder = resolve }) as never)
  fireEvent.click(screen.getByRole('button', { name: 'Move Layer First down' }))
  expect(screen.getByRole('button', { name: 'Save configuration' })).toBeDisabled()
  expect(screen.getByRole('button', { name: 'Delete Layer' })).toBeDisabled()
  expect(screen.getByRole('button', { name: 'Add Layer' })).toBeDisabled()
  expect(screen.getByRole('button', { name: 'Move Layer Second down' })).toBeDisabled()
  finishReorder({ data: [layer('b', 'Second'), layer('a', 'First')] })
  await waitFor(() => expect(screen.getByRole('button', { name: 'Save configuration' })).toBeEnabled())
  let finishSave: (result: unknown) => void = () => { throw new Error('missing resolver') }
  mockUpdate.mockImplementation(() => new Promise((resolve) => { finishSave = resolve }) as never)
  fireEvent.click(screen.getByRole('button', { name: 'Save configuration' }))
  expect(screen.getByRole('button', { name: 'Move Layer First up' })).toBeDisabled()
  expect(mockReorderLayers).toHaveBeenCalledTimes(1)
  finishSave({ data: layer('a', 'First') })
  await waitFor(() => expect(screen.getByRole('button', { name: 'Move Layer First up' })).toBeEnabled())
})
